### ISSUE TITLE
Commit pdfs

### ISSUE THREAD

**Issue by dennisangemi** [jaantollander/pandoc-markdown-latex-pdf-example#1]
Thx for this awesome work! Is there a way to commit pdfs rather than releasing them as artifacts?

**Comment by dennisangemi** [comment]
Resolved https://github.com/dennisangemi/pandoc-md-latex-pdf/blob/master/.github/workflows/build_commit.yml

Delete this:
```
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            output_print.pdf
            output_ereader.pdf
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            output_print.pdf
            output_ereader.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and add this
```
      - name: Commit and push
        run: |-
          git config user.name "PDF-converter"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601=seconds)
          git commit -m "Conversione: ${timestamp}" || exit 0
          git push
```
